/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/axolotl/scene.glb 
Author: None (https://sketchfab.com/None_Yaroslav)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-axolotl-ae0b82612dd84aa081d4c579c63512c7
Title: Minecraft Axolotl
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Axolotlfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Head" position={[150, 10, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[50, 80, 50]} />
                <group name="Body" rotation={[-Math.PI / 2, 0, 0]} scale={[100, 80, 40]} />
                <group name="Spine" position={[-10, 10, 0]} scale={[90, 50, 100]} />
                <group name="Tail" position={[-220, 10, 0]} scale={[120, 50, 100]} />
                <group name="EarsUp" position={[120, 90, 0]} rotation={[0, 1.571, 0]} scale={[80, 30, 100]} />
                <group name="EarsR" position={[120, 30, 110]} rotation={[0, 1.571, 0]} scale={[30, 70, 100]} />
                <group name="EarsL" position={[120, 30, -110]} rotation={[0, 1.571, 0]} scale={[30, 70, 100]} />
                <group name="PawLF" position={[90, -25, -75]} rotation={[Math.PI / 2, 1.571, 0]} scale={[30, 50, 100]} />
                <group name="PawRF" position={[90, -25, 75]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[30, 50, 100]} />
                <group name="PawLB" position={[-50, -30, -75]} rotation={[Math.PI / 2, 1.571, 0]} scale={[30, 50, 100]} />
                <group name="PawRB" position={[-50, -29.833, 75]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[30, 50, 100]} />
                <group name="Armature" position={[-100, -40, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_16">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_18" position={[150, 10, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[50, 80, 50]} />
                    <group name="Object_20" rotation={[-Math.PI / 2, 0, 0]} scale={[100, 80, 40]} />
                    <group name="Object_22" position={[-10, 10, 0]} scale={[90, 50, 100]} />
                    <group name="Object_24" position={[-220, 10, 0]} scale={[120, 50, 100]} />
                    <group name="Object_26" position={[120, 90, 0]} rotation={[0, Math.PI / 2, 0]} scale={[80, 30, 100]} />
                    <group name="Object_28" position={[120, 30, 110]} rotation={[0, Math.PI / 2, 0]} scale={[30, 70, 100]} />
                    <group name="Object_30" position={[120, 30, -110]} rotation={[0, Math.PI / 2, 0]} scale={[30, 70, 100]} />
                    <group name="Object_32" position={[90, -25, -75]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[30, 50, 100]} />
                    <group name="Object_34" position={[90, -25, 75]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[30, 50, 100]} />
                    <group name="Object_36" position={[-50, -30, -75]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[30, 50, 100]} />
                    <group name="Object_38" position={[-50, -29.833, 75]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[30, 50, 100]} />
                    <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Axolotl} skeleton={nodes.Object_19.skeleton} />
                    <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Axolotl} skeleton={nodes.Object_21.skeleton} />
                    <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Axolotl} skeleton={nodes.Object_23.skeleton} />
                    <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Axolotl} skeleton={nodes.Object_25.skeleton} />
                    <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Axolotl} skeleton={nodes.Object_27.skeleton} />
                    <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Axolotl} skeleton={nodes.Object_29.skeleton} />
                    <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Axolotl} skeleton={nodes.Object_31.skeleton} />
                    <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Axolotl} skeleton={nodes.Object_33.skeleton} />
                    <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Axolotl} skeleton={nodes.Object_35.skeleton} />
                    <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Axolotl} skeleton={nodes.Object_37.skeleton} />
                    <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Axolotl} skeleton={nodes.Object_39.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
