/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/dog/dog.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dog/dog.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Shiba_inu_DIF_0.geometry} material={materials.material} rotation={[Math.PI / 2, 0, 0]} scale={0.187} />
      </group>
    </group>
  )
}

useGLTF.preload('/dog.glb')
