/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room5/scene.glb 
Author: hayjaja (https://sketchfab.com/hayjaja)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/its-iso-rooms-all-the-way-down-7a3533ba932e43e0bef16cf94bb0ff61
Title: Its Iso Rooms All The Way Down
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.554, 0.269, -4.008]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Walls} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.WoodFloor} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.WoodTrim} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['CartWheels.001']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Window} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['WoodFloor.001']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.WoodBookshelf} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.TableLegs} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Bookshelf.001']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.MetalBronze} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.CartWheels} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Bookshelf} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.MacNCheese} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Ceramic} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Dirt} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.MetalShiny} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.TVScreen} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.MagazineBlue} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.BookPages} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.MagazineRed} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.BookGreen} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Bush} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Couch} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.BookBrown} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Grass} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.SkinMain} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Mouth} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Claws} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.SkinDark} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.SkinLight} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['MetalGold.001']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Lampshade} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Lamp} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Chair} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Ceramic.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
