/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/monster/scene.glb 
Author: Frog (https://sketchfab.com/RecodorYT)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-monster-39710ebb643f455983226f82680a7a5e
Title: Minecraft Monster
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.359, 1.712, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[0, -0.994, 0]} rotation={[0, 0, 0.087]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} rotation={[0, 0, -0.175]} />
      </group>
      <group position={[-0.243, 1.224, 0]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_1} position={[-0.007, -0.505, 0]} rotation={[0, 0, 0.087]} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_1} position={[-0.007, 0.488, 0]} rotation={[0, 0, -0.175]} />
      </group>
      <group position={[1.344, -0.094, 0.047]}>
        <mesh geometry={nodes.Object_60.geometry} material={materials.material_6} position={[-0.661, 0.956, 0.04]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.material_6} position={[-0.714, 0.843, -0.002]} rotation={[0.174, -0.015, -0.086]} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.material_6} position={[-0.719, 0.727, -0.002]} rotation={[-0.175, 0, 0]} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.material_6} position={[-0.614, 0.845, -0.002]} rotation={[0.175, 0, 0]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.material_6} position={[-0.614, 0.727, -0.002]} rotation={[-0.175, 0, 0]} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.material_6} position={[-0.728, 0.845, 0.071]} rotation={[Math.PI, 0, -2.967]} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.material_6} position={[-0.728, 0.727, 0.071]} rotation={[-Math.PI, 0, 2.967]} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.material_6} position={[-0.661, 0.845, -0.002]} rotation={[0.175, 0, 0]} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.material_6} position={[-0.661, 0.727, -0.002]} rotation={[-0.175, 0, 0]} />
      </group>
      <group position={[0.086, 3.019, -0.133]}>
        <mesh geometry={nodes.Object_79.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.material_7} position={[0, 0, 0.039]} rotation={[0.691, 0.112, 0.134]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.material_7} rotation={[-0.734, -0.118, 0.129]} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.material_7} position={[-0.189, 0.082, -0.061]} rotation={[-Math.PI, 0, -0.175]} />
      </group>
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_2} position={[0.125, 2.449, -0.006]} rotation={[0.262, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.material_2} position={[0.063, 3.078, 0.109]} rotation={[-0.262, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_2} position={[0.063, 3.453, 0.063]} rotation={[-0.129, -0.023, 0.173]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.material_3} position={[-0.424, 2.346, 0.125]} rotation={[-0.215, 0.038, -0.17]} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.material_3} position={[-0.593, 1.39, 0.442]} rotation={[0.258, -0.045, -0.169]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material_4} position={[0.503, 2.203, 0.217]} rotation={[-0.215, 0.038, 0.135]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material_4} position={[0.651, 1.359, 0.396]} rotation={[0.176, 0.086, 0.11]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.material_5} position={[-0.664, 0.927, 0.053]} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.material_5} position={[-0.717, 0.815, 0.011]} rotation={[0.174, -0.015, -0.086]} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.material_5} position={[-0.617, 0.816, 0.011]} rotation={[0.175, 0, 0]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.material_5} position={[-0.664, 0.816, 0.011]} rotation={[0.175, 0, 0]} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.material_5} position={[-0.606, 0.816, 0.084]} rotation={[0, 0, 0.175]} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.material_5} position={[-0.722, 0.699, 0.011]} rotation={[-0.175, 0, 0]} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.material_5} position={[-0.664, 0.699, 0.011]} rotation={[-0.175, 0, 0]} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.material_5} position={[-0.617, 0.699, 0.011]} rotation={[-0.175, 0, 0]} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.material_5} position={[-0.606, 0.699, 0.084]} rotation={[0, 0, -0.175]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.material_8} position={[0, 3.313, -0.25]} rotation={[-0.129, -0.023, 0.173]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.material_8} position={[0, 3.313, -0.25]} rotation={[-0.129, -0.023, 0.173]} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.material_9} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.material_9} position={[-0.367, 0.015, -0.32]} rotation={[-0.218, 0, 0]} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.material_9} position={[-0.367, 0.013, -0.19]} rotation={[0.305, 0, 0]} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.material_9} position={[-0.305, 0.014, -0.322]} rotation={[-0.305, 0, 0]} />
      <mesh geometry={nodes.Object_125.geometry} material={materials.material_9} position={[-0.305, 0.004, -0.193]} rotation={[Math.PI / 8, 0, 0]} />
      <mesh geometry={nodes.Object_127.geometry} material={materials.material_9} position={[-0.243, 0.03, -0.324]} rotation={[-0.219, 0.009, 0.004]} />
      <mesh geometry={nodes.Object_129.geometry} material={materials.material_9} position={[-0.242, 0.013, -0.19]} rotation={[0.305, 0, 0]} />
      <mesh geometry={nodes.Object_131.geometry} material={materials.material_9} position={[-0.734, 0, 0]} />
      <mesh geometry={nodes.Object_133.geometry} material={materials.material_9} position={[0.492, 0.013, -0.19]} rotation={[0.305, 0, 0]} />
      <mesh geometry={nodes.Object_135.geometry} material={materials.material_9} position={[0.492, 0.03, -0.324]} rotation={[-0.219, 0.009, 0.004]} />
      <mesh geometry={nodes.Object_137.geometry} material={materials.material_9} position={[0.367, 0.013, -0.19]} rotation={[0.305, 0, 0]} />
      <mesh geometry={nodes.Object_139.geometry} material={materials.material_9} position={[0.367, 0.015, -0.32]} rotation={[-0.218, 0, 0]} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.material_9} position={[0.43, 0.004, -0.193]} rotation={[Math.PI / 8, 0, 0]} />
      <mesh geometry={nodes.Object_143.geometry} material={materials.material_9} position={[0.43, 0.014, -0.322]} rotation={[-0.305, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
