/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rainbow_dragon/scene.glb 
Author: nayavpongotra (https://sketchfab.com/nayavpongotra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-rainbow-dragon-fca41f4fe75648f0a5be15fc9946c36b
Title: Minecraft rainbow dragon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.438, -0.5]} rotation={[0.087, 0, 0]}>
        <group position={[0, 0, -0.625]} rotation={[-0.087, 0, 0]}>
          <group position={[0, 0, -0.625]} rotation={[-0.087, 0, 0]}>
            <group position={[0, 0, -0.625]} rotation={[-0.087, 0, 0]}>
              <group position={[0, 0, -0.625]} rotation={[-0.087, 0, 0]}>
                <group position={[0, 0, -0.625]} rotation={[-0.087, 0, 0]}>
                  <group position={[0, -0.25, -0.813]} rotation={[-0.262, 0, 0]}>
                    <mesh geometry={nodes.Object_44_1.geometry} material={materials.material_0} position={[0, -0.188, 4.438]} />
                  </group>
                  <mesh geometry={nodes.Object_31_1.geometry} material={materials.material_0} position={[0, -0.438, 3.625]} />
                  <mesh geometry={nodes.Object_33_1.geometry} material={materials.material_0} position={[0, -0.438, 3.625]} />
                  <mesh geometry={nodes.Object_35_1.geometry} material={materials.material_0} position={[0, -0.438, 3.625]} />
                  <mesh geometry={nodes.Object_37_1.geometry} material={materials.material_0} position={[0, -0.438, 3.625]} />
                  <mesh geometry={nodes.Object_39_1.geometry} material={materials.material_0} position={[0, -0.438, 3.625]} />
                  <mesh geometry={nodes.Object_41_1.geometry} material={materials.material_0} position={[0, -0.438, 3.625]} />
                </group>
                <mesh geometry={nodes.Object_26_1.geometry} material={materials.material_0} position={[0, -0.438, 3]} />
                <mesh geometry={nodes.Object_28_1.geometry} material={materials.material_0} position={[0, -0.438, 3]} />
              </group>
              <mesh geometry={nodes.Object_21_1.geometry} material={materials.material_0} position={[0, -0.438, 2.375]} />
              <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} position={[0, -0.438, 2.375]} />
            </group>
            <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} position={[0, -0.438, 1.75]} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[0, -0.438, 1.75]} />
          </group>
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} position={[0, -0.438, 1.125]} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} position={[0, -0.438, 1.125]} />
        </group>
        <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[0, -0.438, 0.5]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[0, -0.438, 0.5]} />
      </group>
      <group position={[0, 1.25, 0.5]}>
        <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} position={[0, -1.25, -0.5]} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} position={[0, -1.25, -0.5]} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.material_0} position={[0, -1.25, -0.5]} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.material_0} position={[0, -1.25, -0.5]} />
      </group>
      <group position={[0.75, 1.188, 0.125]} rotation={[0.031, -0.172, 0.177]}>
        <group position={[3.5, 0, -0.125]} rotation={[0, 0, -Math.PI / 9]}>
          <mesh geometry={nodes.Object_61.geometry} material={materials.material_0} position={[-4.25, -1.188, 0]} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.material_0} position={[-4.25, -1.188, 0]} />
        </group>
        <mesh geometry={nodes.Object_56.geometry} material={materials.material_0} position={[-0.75, -1.188, -0.125]} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[-0.75, -1.188, -0.125]} />
      </group>
      <group position={[-0.75, 1.188, 0.125]} rotation={[0.031, 0.172, -0.177]}>
        <group position={[-3.5, 0, -0.125]} rotation={[0, 0, Math.PI / 9]}>
          <mesh geometry={nodes.Object_71.geometry} material={materials.material_0} position={[4.25, -1.188, 0]} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.material_0} position={[4.25, -1.188, 0]} />
        </group>
        <mesh geometry={nodes.Object_66.geometry} material={materials.material_0} position={[0.75, -1.188, -0.125]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.material_0} position={[0.75, -1.188, -0.125]} />
      </group>
      <group position={[1, 0.5, 2.625]} rotation={[-Math.PI / 3, 0, 0]}>
        <group position={[0, -1.75, 0.063]} rotation={[-0.436, 0, 0]}>
          <group position={[0, -2, -0.125]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Object_82.geometry} material={materials.material_0} position={[-1, 3.25, -2.563]} />
          </group>
          <mesh geometry={nodes.Object_79.geometry} material={materials.material_0} position={[-1, 1.25, -2.688]} />
        </group>
        <mesh geometry={nodes.Object_76.geometry} material={materials.material_0} position={[-1, -0.5, -2.625]} />
      </group>
      <group position={[-1, 0.5, 2.625]} rotation={[-Math.PI / 3, 0, 0]}>
        <group position={[0, -1.75, 0.063]} rotation={[-0.436, 0, 0]}>
          <group position={[0, -2, -0.125]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Object_91.geometry} material={materials.material_0} position={[1, 3.25, -2.563]} />
          </group>
          <mesh geometry={nodes.Object_88.geometry} material={materials.material_0} position={[1, 1.25, -2.688]} />
        </group>
        <mesh geometry={nodes.Object_85.geometry} material={materials.material_0} position={[1, -0.5, -2.625]} />
      </group>
      <group position={[0.75, 0.25, 0.125]} rotation={[-1.134, 0, 0]}>
        <group position={[0, -1.25, 0]} rotation={[Math.PI / 9, 0, 0]}>
          <group position={[0, -1.375, 0]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Object_100.geometry} material={materials.material_0} position={[-0.75, 2.375, -0.125]} />
          </group>
          <mesh geometry={nodes.Object_97.geometry} material={materials.material_0} position={[-0.75, 1, -0.125]} />
        </group>
        <mesh geometry={nodes.Object_94.geometry} material={materials.material_0} position={[-0.75, -0.25, -0.125]} />
      </group>
      <group position={[-0.75, 0.25, 0.125]} rotation={[-1.134, 0, 0]}>
        <group position={[0, -1.25, 0]} rotation={[Math.PI / 9, 0, 0]}>
          <group position={[0, -1.375, 0]} rotation={[-Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Object_109.geometry} material={materials.material_0} position={[0.75, 2.375, -0.125]} />
          </group>
          <mesh geometry={nodes.Object_106.geometry} material={materials.material_0} position={[0.75, 1, -0.125]} />
        </group>
        <mesh geometry={nodes.Object_103.geometry} material={materials.material_0} position={[0.75, -0.25, -0.125]} />
      </group>
      <group position={[0, 0.875, 3.5]}>
        <group position={[0, 0, 0.625]} rotation={[-0.017, 0, 0]}>
          <group position={[0, 0, 0.625]} rotation={[-0.017, 0, 0]}>
            <group position={[0, 0, 0.625]} rotation={[-0.017, 0, 0]}>
              <group position={[0, 0, 0.625]} rotation={[-0.035, 0, 0]}>
                <group position={[0, 0, 0.625]} rotation={[-0.052, 0, 0]}>
                  <group position={[0, 0, 0.625]} rotation={[-0.052, 0, 0]}>
                    <group position={[0, 0, 0.625]} rotation={[-0.017, 0, 0]}>
                      <group position={[0, 0, 0.625]} rotation={[0.017, 0, 0]}>
                        <group position={[0, 0, 0.625]} rotation={[0.035, 0, 0]}>
                          <group position={[0, 0, 0.625]} rotation={[0.052, 0, 0]}>
                            <group position={[0, 0, 0.625]} rotation={[0.052, 0, 0]}>
                              <mesh geometry={nodes.Object_167.geometry} material={materials.material_0} position={[0, -0.875, -10.375]} />
                              <mesh geometry={nodes.Object_169.geometry} material={materials.material_0} position={[0, -0.875, -10.375]} />
                            </group>
                            <mesh geometry={nodes.Object_162.geometry} material={materials.material_0} position={[0, -0.875, -9.75]} />
                            <mesh geometry={nodes.Object_164.geometry} material={materials.material_0} position={[0, -0.875, -9.75]} />
                          </group>
                          <mesh geometry={nodes.Object_157.geometry} material={materials.material_0} position={[0, -0.875, -9.125]} />
                          <mesh geometry={nodes.Object_159.geometry} material={materials.material_0} position={[0, -0.875, -9.125]} />
                        </group>
                        <mesh geometry={nodes.Object_152.geometry} material={materials.material_0} position={[0, -0.875, -8.5]} />
                        <mesh geometry={nodes.Object_154.geometry} material={materials.material_0} position={[0, -0.875, -8.5]} />
                      </group>
                      <mesh geometry={nodes.Object_147.geometry} material={materials.material_0} position={[0, -0.875, -7.875]} />
                      <mesh geometry={nodes.Object_149.geometry} material={materials.material_0} position={[0, -0.875, -7.875]} />
                    </group>
                    <mesh geometry={nodes.Object_142.geometry} material={materials.material_0} position={[0, -0.875, -7.25]} />
                    <mesh geometry={nodes.Object_144.geometry} material={materials.material_0} position={[0, -0.875, -7.25]} />
                  </group>
                  <mesh geometry={nodes.Object_137.geometry} material={materials.material_0} position={[0, -0.875, -6.625]} />
                  <mesh geometry={nodes.Object_139.geometry} material={materials.material_0} position={[0, -0.875, -6.625]} />
                </group>
                <mesh geometry={nodes.Object_132.geometry} material={materials.material_0} position={[0, -0.875, -6]} />
                <mesh geometry={nodes.Object_134.geometry} material={materials.material_0} position={[0, -0.875, -6]} />
              </group>
              <mesh geometry={nodes.Object_127.geometry} material={materials.material_0} position={[0, -0.875, -5.375]} />
              <mesh geometry={nodes.Object_129.geometry} material={materials.material_0} position={[0, -0.875, -5.375]} />
            </group>
            <mesh geometry={nodes.Object_122.geometry} material={materials.material_0} position={[0, -0.875, -4.75]} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.material_0} position={[0, -0.875, -4.75]} />
          </group>
          <mesh geometry={nodes.Object_117.geometry} material={materials.material_0} position={[0, -0.875, -4.125]} />
          <mesh geometry={nodes.Object_119.geometry} material={materials.material_0} position={[0, -0.875, -4.125]} />
        </group>
        <mesh geometry={nodes.Object_112.geometry} material={materials.material_0} position={[0, -0.875, -3.5]} />
        <mesh geometry={nodes.Object_114.geometry} material={materials.material_0} position={[0, -0.875, -3.5]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
