/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cow/scene.glb 
Author: utru (https://sketchfab.com/utru)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-cow-f09ab0765f014c1498d298faaca142c0
Title: Minecraft Cow
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 2.4]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.188, 0.125]}>
            <group position={[0, -0.313, -0.125]}>
              <group position={[0, -0.444, 0.195]}>
                <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[0, -0.056, -0.539]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[0, -0.056, -0.539]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} position={[0, -0.056, -0.539]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} position={[0, -0.056, -0.539]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[0, -0.056, -0.539]} rotation={[Math.PI / 2, 0, 0]} />
              </group>
              <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} rotation={[1.614, 0, 0]} />
            </group>
            <group position={[0, -0.188, -0.688]}>
              <group position={[0, -0.187, -0.054]}>
                <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} position={[0, -0.813, 0.616]} />
                <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[0, -0.813, 0.616]} />
                <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[0, -0.813, 0.616]} />
                <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} position={[0, -0.813, 0.616]} />
              </group>
              <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} rotation={[0.698, 0, 0]} />
              <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} rotation={[0.698, 0, 0]} />
            </group>
            <group position={[0, 0, -0.625]}>
              <group position={[0, -0.25, 0.019]}>
                <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[0, -0.938, 0.481]} />
              </group>
              <group position={[0, -0.25, 0.019]}>
                <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} position={[0, -0.938, 0.481]} />
              </group>
              <group position={[0, -0.094, -0.375]}>
                <group position={[0, -0.125, -0.081]}>
                  <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} position={[0, -0.969, 0.956]} />
                </group>
                <mesh geometry={nodes.Object_44.geometry} material={materials.material_0} position={[0, -1.094, 0.875]} />
              </group>
              <group position={[-0.249, 0.138, -0.094]}>
                <mesh geometry={nodes.Object_50.geometry} material={materials.material_0} position={[-0.001, -0.001, 0]} rotation={[0, 0, Math.PI / 6]} />
              </group>
              <group position={[0.25, 0.138, -0.094]}>
                <mesh geometry={nodes.Object_53.geometry} material={materials.material_0} rotation={[0, 0, -Math.PI / 6]} />
              </group>
              <group position={[-0.25, 0.188, -0.188]} rotation={[-0.14, -0.178, -0.284]}>
                <mesh geometry={nodes.Object_56.geometry} material={materials.material_0} position={[0.25, -1.375, 0.688]} />
                <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0.25, -1.375, 0.688]} />
              </group>
              <group position={[0.25, 0.194, -0.188]} rotation={[-0.14, 0.178, 0.284]}>
                <mesh geometry={nodes.Object_61.geometry} material={materials.material_0} position={[-0.25, -1.381, 0.688]} />
                <mesh geometry={nodes.Object_63.geometry} material={materials.material_0} position={[-0.25, -1.381, 0.688]} />
              </group>
              <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} position={[0, -1.188, 0.5]} />
            </group>
            <group position={[0.25, -0.563, 0.313]}>
              <mesh geometry={nodes.Object_66.geometry} material={materials.material_0} position={[-0.25, -0.625, -0.438]} />
            </group>
            <group position={[-0.25, -0.563, 0.313]}>
              <mesh geometry={nodes.Object_69.geometry} material={materials.material_0} position={[0.25, -0.625, -0.438]} />
            </group>
            <group position={[0.25, -0.563, -0.5]}>
              <mesh geometry={nodes.Object_72.geometry} material={materials.material_0} position={[-0.25, -0.625, 0.375]} />
            </group>
            <group position={[-0.25, -0.563, -0.438]}>
              <mesh geometry={nodes.Object_75.geometry} material={materials.material_0} position={[0.25, -0.625, 0.313]} />
            </group>
            <group position={[-0.031, -0.119, 0.531]}>
              <group position={[0, -0.25, 0]}>
                <mesh geometry={nodes.Object_81.geometry} material={materials.material_0} position={[0, 0.256, 0]} rotation={[Math.PI / 2, 0, 0]} />
                <mesh geometry={nodes.Object_83.geometry} material={materials.material_0} position={[0, 0.256, 0]} rotation={[Math.PI / 2, 0, 0]} />
              </group>
              <mesh geometry={nodes.Object_78.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
