/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shark/scene.glb 
Author: sedona1029 (https://sketchfab.com/sedona1029)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-shark-8c404f3b7675490cb1655f0ac56d9b5a
Title: [Minecraft] Shark
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[8, 2, -9]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_1} />
      </group>
      <group position={[8, 7.5, -9]} rotation={[-Math.PI / 8, 0, 0]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
      </group>
      <group position={[8, 5, 23.5]} rotation={[-Math.PI / 8, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_1} />
      </group>
      <group position={[8, 5, 24.5]} rotation={[Math.PI / 4, 0, 0]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_1} />
      </group>
      <group position={[12, 10, 23]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_1} />
      </group>
      <group position={[12.5, 9.5, 19]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material_1} />
      </group>
      <group position={[11, 1, 13]} rotation={[0, 0, -Math.PI / 4]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} />
      </group>
      <group position={[5, 1, 13]} rotation={[0, 0, Math.PI / 4]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} />
      </group>
      <group position={[13, 9, 15]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.material_1} />
      </group>
      <group position={[13.5, 8.5, 7]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.material_1} />
      </group>
      <group position={[13.5, 8.5, -9]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.material_1} />
      </group>
      <group position={[8, 10, -0.5]} rotation={[Math.PI / 4, 0, 0]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.material_1} />
      </group>
      <group position={[8, 7.75, 1]} rotation={[Math.PI / 8, 0, 0]}>
        <mesh geometry={nodes.Object_40.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} />
      </group>
      <group position={[12, 3, 1]} rotation={[0, 0, -Math.PI / 8]}>
        <mesh geometry={nodes.Object_43.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.material_1} />
      </group>
      <group position={[4, 3, 1]} rotation={[0, 0, Math.PI / 8]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.material_1} />
      </group>
      <mesh geometry={nodes.Object_49.geometry} material={materials.material_1} position={[13, 8, 3]} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
