/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/room/room1.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/room/room1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane" position={[-2.553, 0.312, -0.569]} />
        <group name="Cylinder001" position={[-1.481, 0.855, -2.355]} scale={[0.131, 0.641, 0.131]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.005, 3.621, -0.004]} scale={3.379} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-2.506, 2.136, -1.754]} scale={[0.83, 0.116, 1.556]} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.017']} position={[-2.328, 2.36, -1.695]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.018']} position={[-2.984, 2.6, -1.677]} scale={[-0.098, -0.2, -0.104]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.019']} position={[-3.022, 2.784, -1.68]} scale={[-0.061, -0.211, -0.103]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[-2.961, 2.946, -1.676]} rotation={[0, 0, 1.571]} scale={1.091} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[1.765, 5.08, 0.239]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.014']} position={[-0.866, 4.177, -3.155]} rotation={[0, 0, 1.571]} scale={[0.453, 0.688, 0.167]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[-0.866, 4.177, -3.155]} rotation={[0, 0, 1.571]} scale={[0.453, 0.688, 0.167]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.015']} position={[-0.358, 4.167, -3.157]} rotation={[0.017, 0.026, 1.585]} scale={[0.453, 0.688, 0.167]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.016']} position={[-1.846, 4.956, -3.217]} rotation={[0, 0, 1.571]} scale={[0.453, 0.688, 0.167]} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.013']} position={[2.12, 4.972, -3.296]} rotation={[1.572, 0.035, 3.107]} scale={[-0.564, -0.041, -0.564]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.022']} position={[-3.382, 4.617, 1.341]} scale={[0.087, 1, 1]} />
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.020']} position={[-3.237, 5.722, 1.351]} scale={[0.206, 1, 1]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.004']} position={[-2.395, 2.375, -1.716]} scale={0.127} />
        <mesh name="BézierCurve001" geometry={nodes.BézierCurve001.geometry} material={materials['Material.005']} position={[2.101, 1.655, -2.51]} rotation={[-3.034, 1.095, -1.266]} scale={0.75} />
        <group name="Cube019" position={[2.362, 2.487, -2.933]} rotation={[-2.39, -0.808, -0.596]} scale={[-0.174, -0.086, -0.289]}>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.007']} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={nodes.Cube021_1.material} />
          <mesh name="Cube021_2" geometry={nodes.Cube021_2.geometry} material={materials['Material.006']} />
          <mesh name="Cube021_3" geometry={nodes.Cube021_3.geometry} material={materials['Material.009']} />
          <mesh name="Cube021_4" geometry={nodes.Cube021_4.geometry} material={materials['Material.008']} />
          <mesh name="Cube021_5" geometry={nodes.Cube021_5.geometry} material={materials['Material.010']} />
          <mesh name="Cube021_6" geometry={nodes.Cube021_6.geometry} material={materials['Material.011']} />
          <mesh name="Cube021_7" geometry={nodes.Cube021_7.geometry} material={materials['Material.012']} />
        </group>
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Material.022']} position={[-3.276, 4.932, 1.638]} scale={[0.038, 0.439, 0.439]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.026']} position={[-2.216, 2.376, -0.492]} scale={-0.259} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.025']} position={[-2.403, 2.662, -0.582]} scale={0.042} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.027']} position={[-2.169, 2.365, -2.536]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.317, 0.126, 0.19]} />
        <group name="Torus001" position={[-2.76, 2.439, -2.965]} rotation={[0.153, -0.15, -1.548]} scale={0.083}>
          <mesh name="Torus001_1" geometry={nodes.Torus001_1.geometry} material={nodes.Torus001_1.material} />
          <mesh name="Torus001_2" geometry={nodes.Torus001_2.geometry} material={materials['Material.028']} />
        </group>
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.022']} position={[-3.276, 4.932, 1.638]} scale={[0.038, 0.439, 0.439]} />
        <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.030']} position={[-1.323, 1.597, -1.647]} scale={0.887} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.032']} position={[-1.344, 1.036, -1.651]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.098, -0.403, -0.098]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.031']} position={[-1.353, 0.597, -1.642]} scale={-0.174} />
        <mesh name="Torus007" geometry={nodes.Torus007.geometry} material={materials['Material.029']} position={[-1.323, 1.597, -1.647]} rotation={[Math.PI, Math.PI / 6, -Math.PI / 2]} scale={0.119} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.034']} position={[-0.484, 1.411, -1.64]} scale={-0.095} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.030']} position={[-0.859, 2.559, -1.694]} rotation={[3.138, 0.059, 1.787]} scale={0.887} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.030']} position={[-0.539, 3.525, -1.7]} rotation={[0.017, 0.013, -1.81]} scale={[0.316, 0.316, 0.587]} />
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials['Material.030']} position={[-1.277, 1.723, -1.677]} scale={0.828} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={materials['Material.033']} position={[-1.312, 1.811, -1.671]} scale={[0.077, 0.077, 0.109]} />
        <group name="Cube004" position={[2.257, 2.258, -2.282]} rotation={[-2.159, 1.157, 1.583]} scale={[-0.174, -0.086, -0.289]}>
          <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials['Material.035']} />
          <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={nodes.Cube013_2.material} />
          <mesh name="Cube013_3" geometry={nodes.Cube013_3.geometry} material={materials['Material.036']} />
          <mesh name="Cube013_4" geometry={nodes.Cube013_4.geometry} material={materials['Material.037']} />
          <mesh name="Cube013_5" geometry={nodes.Cube013_5.geometry} material={materials['Material.038']} />
          <mesh name="Cube013_6" geometry={nodes.Cube013_6.geometry} material={materials['Material.039']} />
          <mesh name="Cube013_7" geometry={nodes.Cube013_7.geometry} material={materials['Material.040']} />
          <mesh name="Cube013_8" geometry={nodes.Cube013_8.geometry} material={materials['Material.041']} />
        </group>
        <mesh name="BézierCurve002" geometry={nodes.BézierCurve002.geometry} material={materials['Material.042']} position={[2.15, 1.508, -2.856]} rotation={[2.458, 1.162, -0.896]} />
      </group>
    </group>
  )
}

useGLTF.preload('/room1.glb')
